### ISSUE TITLE
Failed to load plugin when I enable this plugin

### ISSUE THREAD

**Issue by lulunac27a** [name/obsidian-rpg#4]
When I try to enable this plugin, it's said it's failed to load plugin "rpg-stat-tracker".

**Comment by lulunac27a** [comment]
When I checked your code on VSCode, there is no syntax errors at all when I install required type libraries for Obsidian. But I still can't load this plugin. Is there something wrong with your code?

**Comment by name** [comment]
Could I have some more details on this one as I'm not experiencing the same. What platform are you using, any other error messages that might help in troubleshooting?

**Comment by lulunac27a** [comment]
I'm using Obsidian Version 1.6.7 (Installer 1.5.3), which is the latest version. And the only error message is `Failed to load plugin "rpg-stat-tracker"`.

**Comment by lulunac27a** [comment]
Even I create a new vault and followed steps in the Installation steps, it still gets the same error message.

**Comment by lulunac27a** [comment]
I updated Obsidian to the latest version 1.6.7, but I still get the same error.

**Comment by lulunac27a** [comment]
I'm using macOS Sequoia version 15.

**Comment by lulunac27a** [comment]
I'm using Obsidian version 1.7.4, it still gets the same error.

**Comment by lulunac27a** [comment]
Error message from Developer Tools: `Plugin failure: rpg-stat-tracker Error: ENOENT: no such file or directory, open '/Users/lulu/Documents/Obsidian Vault/.obsidian/plugins/obsidian-rpg/main.js'`
